openapi: '3.0.0'
info:
  version: 1.0.0
  title: SmartAssets
servers:
  - url: /api
paths:
  /:
    get:
      description: API home page
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /assets:
    get:
      description: Retrieve all assets
      parameters:
        - name: name
          in: query
          required: false
          schema:
            type: string
        - name: id
          in: query
          required: false
          schema:
            type: number
        - name: quantity
          in: query
          required: false
          schema:
            type: string
        - name: serial
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    post:
      description: Create a new asset.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
             $ref: '#/components/schemas/NewAsset'
          application/json:
            schema:
             $ref: '#/components/schemas/NewAsset'
      responses:
        '200':
          description: Asset created successfully
          content:
            application/json:
              schema:
                type: object
    delete:
      description: Delete all assets
      responses:
        '200':
          description: Assets deleted successfully
          content:
            application/json:
              schema:
                type: object
  /assets/{id}:
    get:
      description: Retrieve asset with specified ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    put:
      description: Update asset with specified ID.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
             $ref: '#/components/schemas/Asset'
          application/json:
            schema:
             $ref: '#/components/schemas/Asset'
      responses:
        '200':
          description: Asset updated successfully
          content:
            application/json:
              schema:
                type: object
    delete:
      description: Delete asset with specified ID.
      responses:
        '200':
          description: Asset deleted successfully
          content:
            application/json:
              schema:
                type: object
  /users:
    get:
      description: Retrieve all users
      parameters:
        - name: username
          in: query
          required: false
          schema:
            type: string
        - name: email
          in: query
          required: false
          schema:
            type: string
        - name: phone
          in: query
          required: false
          schema:
            type: string
        - name: name
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
  /users/{id}:
    get:
      description: Retrieve user with specified ID
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
    put:
      description: Update user with specified ID.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
             $ref: '#/components/schemas/User'
          application/json:
            schema:
             $ref: '#/components/schemas/User'
      responses:
        '200':
          description: User updated successfully
          content:
            application/json:
              schema:
                type: object
    delete:
      description: Delete user with specified ID.
      responses:
        '200':
          description: User deleted successfully
          content:
            application/json:
              schema:
                type: object
  /users/signin:
    post:
      description: Create a new user.
      security: []  
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
             $ref: '#/components/schemas/Login'
          application/json:
            schema:
             $ref: '#/components/schemas/Login'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
  /users/signup:
    post:
      description: Create a new user.
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
             $ref: '#/components/schemas/SignUp'
          application/json:
            schema:
             $ref: '#/components/schemas/SignUp'
      responses:
        '200':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object


components:
  schemas:
    Asset:
      properties:
        name:
          type: string
        description:
          type: string
        published:
          type: boolean
    NewAsset:
      required:
        - name
      properties:
        name:
          type: string
        description:
          type: string
        published:
          type: boolean
    Login:
      required:
        - username
        - password
      properties:
        username:
          type: string
        password:
          type: string
    SignUp:
      required:
        - username
        - email
        - password
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
        name:
          type: string
        admin:
          type: boolean
        phone:
          type: string
        location:
          type: string
        title:
          type: string
    User:
      properties:
        username:
          type: string
        email:
          type: string
        password:
          type: string
        role:
          type: string
        name:
          type: string
        admin:
          type: boolean
        phone:
          type: string
        location:
          type: string
        title:
          type: string
    Error:
      required:
        - success
        - code
        - errors
        - messages
        - result
      properties:
        success:
          type: boolean
        code:
          type: integer
          format: int32
        errors:
          type: array
        messages:
          type: array
        result:
          type: object
        

  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - ApiKeyAuth: [] 